#!/bin/bash

# Config
# ======

# Where to look for wid files:
TMPDIR="$XDG_RUNTIME_DIR/drawers.wids/"

# Find and show/hide the window if it exists
# ==========================================

NAME=$1

if [[ -e $TMPDIR$NAME ]]; then
     read -r WINDOW < "$TMPDIR$NAME"

    # Window exists? Show/hide it and we're done.
    if wattr $WINDOW; then
        bringwindow -R -t $WINDOW
        exit
    fi
fi

# No window to show/hide, better create it. Do setup for that.
# ============================================================

# only first head for now
CFG=$(xrandr | grep -m 1 primary || xrandr | grep -m 1 connected)
read -r SCR_WIDTH SCR_HEIGHT SCR_LEFT SCR_TOP < <(echo "$CFG" | grep -o '\s[0-9x+]\+' | head -n 1 | tr 'x+' '  ')

SIDE=$2
WIDTH=$3
HEIGHT=$4

shift 4

# Handle fractions of screen size for width and height
# ====================================================

if [[ $WIDTH == *% ]]; then
    WIDTH=${WIDTH:0:-1} # chomp '%'
    WIDTH=$(( (WIDTH*10*SCR_WIDTH)/1000 ))
fi

if [[ $HEIGHT == *% ]]; then
    HEIGHT=${HEIGHT:0:-1} # chomp '%'
    HEIGHT=$(( (HEIGHT*10*SCR_HEIGHT)/1000 ))
fi

# Figure out where to put the window
# ==================================

TOP_ADJ=$(( (SCR_HEIGHT-HEIGHT)/2 ))
LEFT_ADJ=$(( (SCR_WIDTH-WIDTH)/2 ))

case $SIDE in
    "left")
        LEFT=$SCR_LEFT
        TOP=$(( SCR_TOP + TOP_ADJ ))
    ;;
    "right")
        LEFT=$(( SCR_WIDTH - WIDTH ))
        TOP=$(( SCR_TOP + TOP_ADJ ))
    ;;
    "bottom")
        LEFT=$(( SCR_LEFT + LEFT_ADJ ))
        TOP=$(( SCR_HEIGHT - HEIGHT ))
    ;;
    "top")
        LEFT=$(( SCR_LEFT + LEFT_ADJ ))
        TOP=$SCR_TOP
esac

# Create the window
# =================


WINDOW=$(xtoolwait -wid -noprop $COMMAND)
mkdir -p $TMPDIR
echo $WINDOW > $TMPDIR$NAME

wtp $LEFT $TOP $WIDTH $HEIGHT $WINDOW
