#!/bin/bash

# Config
# ======

# Where to look for wid files:
TMPDIR="$XDG_RUNTIME_DIR/drawers.wids/"

# Find and show/hide the window if it exists
# ==========================================

NAME=$1

if [[ -e $TMPDIR$NAME ]]; then
     read -r WINDOW < "$TMPDIR$NAME"

    # Window exists? Show/hide it and we're done.
    if wattr "$WINDOW"; then
        #wmctrl -i -R $WINDOW
        #wmctrl -i -R $WINDOW -b toggle,hidden
        # Buggy wmctrl doesn't always focus the window when toggling, so do our own toggle logic:
        if xprop -id "$WINDOW" | grep -q '_NET_WM_STATE_HIDDEN'; then
            wmctrl -i -r "$WINDOW" -b remove,hidden
            wmctrl -i -R "$WINDOW"
        else
            wmctrl -i -R "$WINDOW" -b add,hidden
        fi
        exit
    fi
fi

# No window to show/hide, better create it. Do setup for that.
# ============================================================

# no xinerama for now
CFG=($(wattr whxy $(lsw -r)))
SCR_WIDTH=${CFG[0]}
SCR_HEIGHT=${CFG[1]}
SCR_LEFT=${CFG[2]}
SCR_TOP=${CFG[3]}

SIDE=$2
WIDTH=$3
HEIGHT=$4

shift 4

# Handle fractions of screen size for width and height
# ====================================================

if [[ $WIDTH == *% ]]; then
    WIDTH=${WIDTH:0:-1} # chomp '%'
    WIDTH=$(( (WIDTH*10*SCR_WIDTH)/1000 ))
fi

if [[ $HEIGHT == *% ]]; then
    HEIGHT=${HEIGHT:0:-1} # chomp '%'
    HEIGHT=$(( (HEIGHT*10*SCR_HEIGHT)/1000 ))
fi

# Figure out where to put the window
# ==================================

TOP_ADJ=$(( (SCR_HEIGHT-HEIGHT)/2 ))
LEFT_ADJ=$(( (SCR_WIDTH-WIDTH)/2 ))

case $SIDE in
    "left")
        LEFT=$SCR_LEFT
        TOP=$(( SCR_TOP + TOP_ADJ ))
    ;;
    "right")
        LEFT=$(( SCR_WIDTH - WIDTH ))
        TOP=$(( SCR_TOP + TOP_ADJ ))
    ;;
    "bottom")
        LEFT=$(( SCR_LEFT + LEFT_ADJ ))
        TOP=$(( SCR_HEIGHT - HEIGHT ))
    ;;
    "top")
        LEFT=$(( SCR_LEFT + LEFT_ADJ ))
        TOP=$SCR_TOP
esac

# Create the window
# =================

$@ &
WINDOW=$(wew | grep -m 1 '^16:' | cut -d: -f2)
xdotool set_window --role "drawer" $WINDOW
sleep 0.5
echo $WINDOW
mkdir -p "$TMPDIR"
echo "$WINDOW" > "$TMPDIR$NAME"

xdotool windowmove $WINDOW $LEFT $TOP windowsize $WINDOW $WIDTH $HEIGHT windowfocus $WINDOW windowraise $WINDOW
