#!/usr/bin/env python2

import re
import os
import sys
import subprocess


class Link():
    def __init__(self, target, name, orcsFile, line):
        self.target = target
        self.name = name
        self.orcsFile = orcsFile
        self.isDir = False
        self.children = []
        self.line = line

def shellParam(s):
    return "'" + s.replace("'", "''") + "'"

# Workaround for Python's generally-horrible backslash-handling
def wsEscape(s):
    res = ''
    for ch in s:
        if ch.isspace():
            # chr(92) = '\' - we can't even place a single backslash in a string constant
            res += chr(92)
        res += ch

    return res

# Find all files under a dir
# Don't include dirs in the result
# Google recursive directory walking in python if you think this sucks
def find(path):
    path = chompSlash(path)
    lines = [ line[len(path)+1:] for line in subprocess.check_output('find '+shellParam(path)+' -not -type d', shell=True).split('\n') if line]
    return [ line for line in lines if line.strip()]
        
def chompSlash(path):
    while path.endswith('/'):
         path = path[:-1]

    return path


def canonical(path):
    return chompSlash(os.path.abspath(os.path.expanduser(path)))

# read the link at path and get an absolute path to the file it's pointing to
def absReadLink(path):
    target = os.readlink(path)

    if not target.startswith('~') and not target.startswith('/'):
        target = os.path.join(os.path.dirname(path), target)

    return canonical(target)

def isChildPath(container, contained):
    container = canonical(container)
    contained = canonical(contained)

    #print "Checking containment:", container, contained

    
    if container == contained:
        return True

    return contained.startswith(container+'/')

def cdToRealFile(path):
    realdir = os.path.dirname(os.path.realpath(canonical(path)))
    os.chdir(realdir)
    return realdir

def compile(path):
    oldDir = os.getcwd()
    realdir = cdToRealFile(path)

    print '=== Compiling '+path+' (actual dir '+realdir+')'
    
    for idx, line in enumerate(open(canonical(path)).readlines()):
        parts = re.split(r'(?<!\\)\s', line)
        command = parts[0].strip()
           
        if command=='link':            
            link = Link(canonical(parts[1]), canonical(parts[2]), path, idx)
            
            if link.name in links:
                print "potential override:" + link.name + '->' + link.target

            if os.path.isdir(link.target):
                link.isDir = True
                link.children = []
                dirs[link.name] = link
                for f in find(canonical(link.target)):
                    newLink = Link(os.path.join(link.target, f), os.path.join(link.name, f), path, idx)
                    links[newLink.name] = newLink
            else:
                links[link.name] = link
            
        elif command=='unmanage':
            dead = canonical(parts[1])
            for name in links.keys():
                if isChildPath(dead, name):
                    del links[name]
            
            for name in dirs.keys():
                if isChildPath(dead, name):
                    del dirs[name]
        elif command=='include':
            compile(parts[1])

    print '=== Done ' + realdir
    os.chdir(oldDir)

def isManaged(name):
    if not os.path.islink(name):
        return False

    for d in dirs.values():
        if isChildPath(d.name, name):
            return d

    for link in links.values():
        if isChildPath(link.name, name):
            return link

def doCopy(link):
    print "  copying " + link.name + " to " + link.target
    os.system("cp " + shellParam(link.name) + " " + shellParam(link.target))

def doRemove(link):
    print "  removing " + link.name
    os.remove(link.name)

def doLink(link):
    print "  linking " + link.target + " to " + link.name
    # or we can handle the exceptions from os.makedirs
    dirPath = canonical(os.path.dirname(link.name))
    if dirPath: os.system("mkdir -p "+ shellParam(dirPath))
    os.symlink(os.path.relpath(canonical(link.target), dirPath), canonical(link.name))

def process():
    # construct directory images
    for link in links.values():
        for d in dirs.values():
            if isChildPath(d.name, link.name):
                d.children.append(link)

    # actually link the files
    for link in links.values():        
        actions = []
        if not os.path.lexists(canonical(link.target)):
            print '** WARNING: nonexistent link target ' + link.target + ' while linking ' + link.name
    
        if os.path.lexists(canonical(link.name)):
            if not os.path.islink(canonical(link.name)):
                print "Link replaced by file:", link.target, link.name, link.isDir
                actions = [doCopy, doRemove, doLink]
            else:
                if not canonical(link.target) == canonical(absReadLink(link.name)):
                    print 'Updating link ' +  link.target + ' -> ' + link.name
                    print canonical(link.target)
                    print canonical(absReadLink(link.name))
                    actions = [doRemove, doLink]
                else:
                    if False: print "Already linked:", link.name
        else:
            actions = [doLink]

        for action in actions:
            action(link)

    # check our work and clean away broken links
    for d in dirs.values():
        actual = {}
        for path in find(d.name):
            actual[canonical(os.path.join(d.name, path))] = True            

        for link in d.children:
            if canonical(link.name) in actual:
                del actual[canonical(link.name)]
            else:
                print "WARNING: failed to create link", link.name

        for name in actual.keys():
            if os.path.lexists(name) and isManaged(name):
                print 'Removing deleted link:', name
                doRemove(Link(None, name, None, None))
            else:
                targ = os.path.relpath(name, canonical(d.name))
                print "Found untracked file " + name + " in tracked directory " + d.name + ", tracking in " + d.target + " as " + targ
                l = Link(os.path.join(canonical(d.target), targ), name, None, None)
                print l.target, l.name
                os.renames(l.name, l.target)
                doLink(l)


#### MAIN ####

links = {} # global because the unmanage command may modify the entire links array
dirs = {}

launchDir = os.getcwd()
sourceFile = '~/.orcsfile'
homeDir = os.path.dirname(canonical(sourceFile))

compile(sourceFile)

#for link in links.values():
#    print link.name + '->' + link.target

os.chdir(homeDir)
print 'Launch dir:', canonical(launchDir)
print 'Working dir:', homeDir

# sigh, python, sigh
cmd = sys.argv[1] if len(sys.argv) > 1 else None

if cmd == 'track':
    cdToRealFile(sourceFile)

    newFile = sys.argv[2]
    dest = ''
    if len(sys.argv) > 3: dest = sys.argv[3]

    print 'Track ' + newFile + ' in ' + (dest or '.')

    link = isManaged(newFile)
    if link:
        print newFile + ' is already managed by ' + link.orcsFile + ':' + link.line
        exit()

    cwd = os.path.relpath(launchDir, homeDir)

    # is it already relative to $HOME?
    if newFile.startswith('~/'):
        pathToLink = newFile[2:]
    else:
        pathToLink = os.path.normpath(os.path.join(cwd, newFile))

    # prepending './' in this manner makes absolute paths relative without changing relative ones
    pathToTarget = os.path.normpath(os.path.join(dest, './'+pathToLink))
    
    link = Link(pathToTarget, '~/'+pathToLink, None, None) 

    print 'Moving ' + wsEscape(canonical(link.name)) + ' to ' + wsEscape(canonical(link.target))
    os.renames(canonical(link.name), canonical(link.target))

    with(open(canonical(sourceFile), 'a')) as f: f.write('link ' + wsEscape(link.target) + ' ' + wsEscape(link.name) + '\n')

    print 'Remember to run `orcs` to create links!'
else:
    print 'Performing sync...'
    process()
