#!/bin/bash

LAST_EVENT_FILE="$HOME/.raction_last_event"
RACTIONS="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/ractions"

OP=$1
shift

case $OP in
    handle)
        echo "$( logdate ): Processing $ES_FIELD_EVENT..."

        if [[ -n $ES_FIELD_ID ]]; then
            printf "%s" "$ES_FIELD_ID" > "$LAST_EVENT_FILE"
        else
            echo "Warning: got event with no ID." >&2
        fi

        if [[ -z "$ES_FIELD_HOST" ]] || ishost "$ES_FIELD_HOST"; then
            echo "    we are the target host"
        
            if which ractiond-local &> /dev/null && ractiond-local "$@"; then exit; else
                echo "    ...not cancelled by raction-local."
                echo "    Executing $RACTIONS/$ES_FIELD_EVENT"
                "$RACTIONS/$ES_FIELD_EVENT"
            fi
            if [[ $ES_FIELD_EVENT != 'ack' ]]; then
                raction ack "$ES_FIELD_ID"
            fi
        fi
        echo "Done processing $ES_FIELD_EVENT"
    ;;
    start)
        while true; do            
            diewithparent "$0" run "$@"
            echo "$( logdate ): connection lost, reconnecting in 3s..." >&2
            sleep 3
        done
    ;;
    run)
        canx && havenet && feedback "ractiond connecting..."

        AFTER=$(cat "$LAST_EVENT_FILE")
        [[ -z "$AFTER" ]] && AFTER=$( date +%s.%N )
        echo "AFTER=$AFTER"

        if [[ '-local' == "$1" ]]; then
            ACTION='local_tail'
        else
            ACTION='tail'
        fi

        diewithparent rclip -c actions $ACTION -raw -after "$AFTER" -f | decode-es "$0" handle "$@"
        canx && havenet && feedback "ractiond connection lost"
    ;;
esac
