#!/bin/bash

LAST_EVENT_FILE="$HOME/.raction_last_event"
POKED_FILE="$HOME/.raction_poked"

OP=$1
shift

case $OP in
    handle)
        echo "`logdate`: Processing $EVENT..."

        if [[ -n $ID ]]; then printf "%s" "$ID" > $LAST_EVENT_FILE; fi

        if (printf "_%s" "$META" | grep -qi 'host:'`hostname`) || (printf "_%s" "$META" | grep -qiv 'host:\w'); then
            echo "    we are the target host"
        
            if which raction-local &> /dev/null && raction-local $@; then exit; else
                echo "    Not cancelled by raction-local."
                case $EVENT in
                    poke)
                        (
                           USE_LEDS=true
                           # don't blink if a horrible busted PS/2->USB adapter is present
                           if lsusb | grep -qi PCPlay; then USE_LEDS=false; fi
        
                            rm "$POKED_FILE" &> /dev/null
                            NID='none'
                            while ! [ -f $POKED_FILE ]; do
                                # constantly recreate notification, for maximum annoyance
                                NID=$(notify-desktop -r $NID -u critical "<b>** INCOMING POKE **</b><br><br>$DATA")
                                $USE_LEDS && xset led 3
                                sleep 0.5
                                $USE_LEDS && xset -led 3
                                sleep 0.25
                            done
                            notify-desktop -r $NID -t 100 "going away now." > /dev/null
                        ) &
                    ;;

                    poked)
                        date +%s.+N > $POKED_FILE
                    ;;

                    note)
                        printf "%s: %s" "$TIME" "$DATA" >> $HOME/writing/notes.txt
                        notify-desktop -t 0 "$DATA" > /dev/null
                    ;;

                    tasksync) task sync;;
                    badtunnel)
                        killall badtunnel;
                        (nohup badtunnel > $HOME/.cache/badtunnel.log) &;;
                    ack) printf "    Got ack: %s, %s\n" "$META" "$DATA";;
                    *) printf "    Unrecognized event '%s'." >&2 ;;
                esac
            fi
            if [[ $EVENT != 'ack' ]]; then
                raction ack "$ID"
            fi
        fi
    ;;
    start)
        while true; do
            diewithparent $0 run $@
            echo "`logdate`: connection lost, reconnecting in 3s..." >&2
            sleep 3
        done
    ;;
    run)
        read AFTER < $LAST_EVENT_FILE
        [[ -z $AFTER ]] && AFTER=`date +%s.%N`
        echo "AFTER=$AFTER"

        if [[ '-local' == $1 ]]; then
            ACTION='local_tail'
        else
            ACTION='tail'
        fi

        diewithparent rclip --test -c actions $ACTION -raw -after $AFTER -f | decode-es $0 handle $@
    ;;
esac
