#!/bin/bash

if [[ '-local' == $1 ]]; then
    ACTION='local_put'
    shift
else
    ACTION='put'
fi

EVENT=$1
shift

FROM="from:$USER@`hostname`"
CUSTOM=''
while [[ -n $1 ]]; do
    case $1 in
        '-from')
            FROM="from:$2"
            shift 2
        ;;
        '-f')
            CUSTOM+="-f $2 "
            shift 2
        ;;
        '-h')
            CUSTOM+="-f host:$2 "
            shift 2
        ;;
        *) break;;
    esac
done

if [[ $1 == '-' ]]; then
    DATA=`cat`
else
    DATA=$@
fi

printf "%s" "$DATA" | rclip -c actions $ACTION -e $EVENT -f $FROM $CUSTOM
