#!/bin/bash

if [ -t 1 ]; then
    OHL="\033[1;34m"
    MHL="\033[1;30m"
    EHL="\033[1;31m"
    UNHL="\033[00m"
fi

case $1 in
    '--handle')
        case $ES_FIELD_EVENT in
            'ack') ;;
            *)                
                if [[ "$ES_FIELD_FROM" == *"$USER"* ]]; then
                    HL=$MHL
                else
                    HL=$OHL
                fi
                EDATE="${ES_FIELD_TIME:4}"
                printf "$HL$ES_FIELD_EVENT from ${ES_FIELD_FROM%%@*} at ${EDATE%% *}: $UNHL\n%s\n\n" "$ES_FIELD_DATA"
            ;;
        esac
        echo "$ES_FIELD_ID" > "$AFTER_FILE"
        exit
    ;;
    '--nowrap')
        export AFTER_FILE="/tmp/rchat_after_$$"
        echo "$(($(date +%s)-60*60*24))" > $AFTER_FILE
        SELF=$$
        (
            while true; do
                rclip -c actions tail -raw -after "$(cat $AFTER_FILE)" -f | decode-es "$0" --handle
                printf "%sConnection lost. Reconnecting...%s\n" "$EHL" "$UNHL"
            done
            kill "$SELF"
        ) &
        while read INITIAL LINE; do
            case $INITIAL in
                /*)
                    printf "%s" "$LINE" | raction "${INITIAL:1}" -
                ;;
                *)
                    printf "%s %s" "$INITIAL $LINE" | raction chat - > /dev/null
                ;;
            esac > /dev/null
        done
    ;;
esac

srw "$0" --nowrap
