#!/bin/bash

# Setup
LOCAL_CMD=$0
REMOTE_CMD="ssh lsh.io bash --login rclip"
CMD_ARGS=""
FEEDBACK_CMD="true"

[[ -e `which notify-send` ]] && [[ -n $DISPLAY ]] && FEEDBACK_CMD="notify-send"

CLIP_BASE="$HOME/rclip"

# parse args
while [[ -n $1 ]]; do
    ARG=$1
    shift
    case $ARG in
        '-c') 
            CLIP_NAME=$1
            CLIP_BASE+="."
            CMD_ARGS+=" -c $CLIP_NAME"
            shift
        ;;
        *) 
            OP=$ARG
            break
        ;;
    esac
done

CLIP_FILE="${CLIP_BASE}${CLIP_NAME}.clip"
LOG_FILE="${CLIP_BASE}${CLIP_NAME}.log"

# hackily handle selection choice for copy/paste
case $1 in
    primary|secondary|clipboard)
        SELECTION=$1
        shift
    ;;
    *) SELECTION="clipboard" ;;
esac

LOCAL_CMD+=$CMD_ARGS
REMOTE_CMD+=$CMD_ARGS

# actually do anything
case $OP in
    copy) 
        (xclip -o -selection $SELECTION | $LOCAL_CMD put $@ &&\
        $FEEDBACK_CMD "rclip: uploaded $SELECTION") ||\
        $FEEDBACK_CMD "rclip: failed to upload"
    ;;
    paste)
        ($LOCAL_CMD get $@ | xclip -i -selection $SELECTION &&\
        $FEEDBACK_CMD "rclip: downloaded clip to $SELECTION") ||\
        $FEEDBACK_CMD "rclip: failed to download."
    ;;
    put) $REMOTE_CMD local_put $@;;
    get) $REMOTE_CMD local_get $@;;
    loop) $REMOTE_CMD local_loop $@;; 
    tail) $REMOTE_CMD local_tail $@;;
    io)
        $LOCAL_CMD tail $@ &
        while read MSG; do
            echo "$MSG" | $LOCAL_CMD put $@
        done
        kill %1
    ;;
    local_put)
	DATE=`logdate`
	if [[ $1 == '-a' ]]; then
            cat > $CLIP_FILE
        else
            echo -e "\n======[$DATE | $@]=====" >> $LOG_FILE
            tee -a $LOG_FILE > $CLIP_FILE
        fi
    ;;    
    local_get) cat $CLIP_FILE;;
    local_tail) tail -f -n +0 $LOG_FILE;;
esac
