#!/bin/bash

# Setup
LOCAL_CMD=$0
REMOTE_CMD="ssh lsh.io"
CMD_ARGS=""
FEEDBACK_CMD="true"

[[ -e `which notify-send` ]] && [[ -n $DISPLAY ]] && FEEDBACK_CMD="notify-send"

CLIP_BASE="$HOME/rclip"

# parse args
while [[ -n $1 ]]; do
    ARG=$1
    shift
    case $ARG in
        '-c') 
            CLIP_NAME=$1
            CLIP_BASE+="."
            CMD_ARGS+=" -c $CLIP_NAME"
            shift
        ;;
        *) 
            OP=$ARG
            break
        ;;
    esac
done

CLIP_FILE="${CLIP_BASE}${CLIP_NAME}.clip"
LOG_FILE="${CLIP_BASE}${CLIP_NAME}.log"

# hackily handle selection choice for copy/paste
case $1 in
    primary|secondary|clipboard)
        SELECTION=$1
        shift
    ;;
    *) SELECTION="clipboard" ;;
esac

LOCAL_CMD+=$CMD_ARGS
REMOTE_CMD+=$CMD_ARGS

# actually do anything
case $OP in
    copy) 
        (xclip -o -selection $SELECTION | $LOCAL_CMD put $@ &&\
        $FEEDBACK_CMD "rclip: uploaded $SELECTION") ||\
        $FEEDBACK_CMD "rclip: failed to upload"
    ;;
    paste)
        ($LOCAL_CMD get $@ | xclip -i -selection $SELECTION &&\
        $FEEDBACK_CMD "rclip: downloaded clip to $SELECTION") ||\
        $FEEDBACK_CMD "rclip: failed to download."
    ;;
    note) echo "$@" | $LOCAL_CMD put -a;;
#    put) $REMOTE_CMD local_put $@;;
#    get) $REMOTE_CMD local_get $@;;
#    tail) $REMOTE_CMD local_tail $@;;
    io)
        $LOCAL_CMD tail $@ &
        while read MSG; do
            echo "$MSG" | $LOCAL_CMD put $@
        done
        kill %1
    ;;
    put)
	if [[ $1 == '-a' ]]; then
            $REMOTE_CMD bash -l -c "tee -a $LOG_FILE >> $CLIP_FILE"
        else
            # confusingness here: escaping subsitution markers makes them be interpreted by the remote bash
            (cat <<_putscript_
                DATE=\`date +'%Y%m%d:%H%M.%S (epoch+%s)'\`
                echo -e "\n======[\$DATE | $@]======" >> $LOG_FILE;
                tee -a $LOG_FILE > $CLIP_FILE

_putscript_
            cat) | $REMOTE_CMD bash -l
        fi
    ;;    
    get) $REMOTE_CMD cat $CLIP_FILE;;
    tail) $REMOTE_CMD tail -f -n +0 $LOG_FILE;;
    *) echo "Unrecognized subcommand: $OP"; exit 1;;
esac
