#!/bin/sh

BRANCH=$(git branch | scut 1)
OLDBRANCH=$BRANCH

if [ "$1" = "-b" ]; then
    BRANCH=$2
    shift 2

    git stash
    git checkout -B "$BRANCH"
    git stash pop
fi  

echo "Pushing $* to $BRANCH"

git add "$@"
echo "Pushing ${*} at $(date)" | git commit -F -
git push -u origin "$BRANCH"
git checkout "$OLDBRANCH"
