#!/bin/sh

stateProperty=DESKTOPS_WINDOWS

getState() {
    xprop -root $stateProperty | sed "s/$stateProperty.*= //"
}

putState() {
    xprop -root -format $stateProperty 8s -set $stateProperty "$(cat)"
}

getCurDesk() {
    xprop -root _NET_CURRENT_DESKTOP
}

withoutWin() { 
    getState | grep -v "win=$1"
}

winToDesk() {
    win="$1"
    desk="$2"

    {
        withoutWin $win
        printf 'desk=%s win=%s\n' "$desk" "$win" 
    } | putState
    
    xprop -id $win -format _NET_WM_DESKTOP 32c -set _NET_WM_DESKTOP $1
}

getDeskWins() {
    case $1 in
        -v) minusV=-v;;
    esac

    getState | grep $minusV "desk=$2" | grep -o "win=\S\+" | cut -d'=' -f2
}

mapDesk() {
    getDeskWins $1 | xargs mapw -m
    getDeskWins -v $1 | xargs mapw -u
    xprop -root -format _NET_CURRENT_DESKTOP 32c -set _NET_CURRENT_DESKTOP $1
}

op="$1"
shift
case "$op" in
    mv) winToDesk $1 $2;;
    rm) withoutWin $1 | putState;;
    map) mapDesk $1;;
    *) echo "Usage: sdesk [mv|rm|map] [WINDOW_ID] DESK_ID";;
esac
    
