#!/bin/bash

CACHE="$HOME/.cache/sesh.state"
echo "Using cache file $CACHE"
munge() {
    sed -e 's/^Inbox[^-]*\(- [^@]\+@[^ ]\+ -\).*$/\1/g' \
        -e 's/^Slack -.*$/Slack -/g' \
        -e 's/^.*- Discord$/- Discord/g' \
        -e 's/^\(DAT Solutions - Calendar -\).*$/\1/g' \
        -e 's/|/\\|/g' \
        -e 's/\-/\\-/g' \
        -e 's/\[/\\[/g' \
        -e 's/\./\\./g' \
        -e 's/(/\\(/g'
}

case $1 in
    load)
        shift
        while read -r WIN; do
            TITLE=$(echo "$WIN" | scut 1-$ | munge)
            DESK=$(echo "$WIN" | scut 0)
            echo "Moving to $DESK: $TITLE"
            [ "$1" = '-n' ] || xdotool search "$TITLE" set_desktop_for_window "$DESK"
        done < "$CACHE"
        echo "State loaded."
    ;;
    save)
        paste -d ' ' <(xdotool search . get_desktop_for_window %@) <(xdotool search . getwindowname %@) | grep -v '^-1' > "$CACHE"
        echo "State saved."
    ;;
    *)
        echo "USAGE: sesh [save|load] [-n]"
    ;;
esac
