#!/bin/bash

CACHE="$HOME/.cache/sesh.state"
echo "Using cache file $CACHE"
munge() {
    sed 's/Inbox ([,0-9]\+).\+@gmail.com//' | sed 's/^[^|]\+| \(.*Slack.*\)/\1/' | sed 's/([^)]\+)//g'
}

case $1 in
    load)
        shift
        while read -r WIN; do
            TITLE=$(echo "$WIN" | scut 1-$ | munge)
            DESK=$(echo "$WIN" | scut 0)
            echo "Moving to $DESK: $TITLE"
            [ "$1" = '-n' ] || wmctrl -r "$TITLE" -t "$DESK"
        done < "$CACHE"
        echo "State loaded."
    ;;
    *)
        wmctrl -l | scut 1,3-$ > "$CACHE"
        echo "State saved."
    ;;
esac
