#!/bin/sh

DEST_DIR="$HOME/share"
DIR_SUFFIX=".priv"

SSH="ssh lsh.io"
REMOTE_CMD="$SSH bash --login"

fullpath() {
    echo "$DEST_DIR$DIR_SUFFIX/$@"
}

urlpath() {
    echo "https://lsh.io:3000/share$DIR_SUFFIX/$@"
}

if [[ "-local" == "$1" ]]; then
    shift

    if [[ "get" == "$1" ]]; then
        echo "Getting `fullpath $2`" >&2
        cat "`fullpath $2`"
        exit
    fi
    
    while getopts 'pqefn:bu:' opt; do
        case $opt in
            p) DIR_SUFFIX=".pub";;
            q) QUIET=true;;
            n) FILENAME="$OPTARG";;
            b) BARE=true;;
            f) OVERWRITE=true;;
	    u) FROM="-from $OPTARG";;
        esac
    done
    shift $OPTIND


    [[ -z "$FILENAME" ]] && FILENAME=`randstr`
    OUT_FILE="$FILENAME"

    while [[ -z "$OVERWRITE" ]] && [[ -s `fullpath "$OUT_FILE"` ]]; do
        OUT_FILE="share_`randstr`_$FILENAME"
    done

    cat > "`fullpath $OUT_FILE`"

    if [[ "true" == "$BARE" ]]; then
        RESULT="$OUT_FILE"
    else
        RESULT="$(urlpath $OUT_FILE)"
    fi

    echo "$RESULT"

    if [[ "true" != "$QUIET" ]]; then
        raction upload $FROM -f "url:`urlpath $OUT_FILE`" "$OUT_FILE" > /dev/null
    fi
else
    FROM="-u $USER@$HOST"
    if [[ "get" != "$1" ]] && [[ "-" != "$1" ]]; then
        IN_FILE="$1"
        shift
        $REMOTE_CMD $0 -local $FROM -n `basename "$IN_FILE"` $@ < "$IN_FILE"
    else
        $REMOTE_CMD $0 -local $FROM $@
    fi
fi
