#!/usr/bin/env bash

url_encode() {
    if test -n "$1"; then
        printf "%s" "$1" | url_encode
    else
        curl -Gso /dev/null -w %{url_effective} --data-urlencode @- "" | cut -c 3-
    fi
}

conf=$(projfile shwitter.conf)
if test "$1" = "-c"; then
   conf="$2"
   shift 2
fi

source "$conf"

api_call() {
    once=$RANDOM
    ts=$(date +%s)
    hmac="$secret&$token_secret"

    method="$1"
    url="$2"
    shift 2
    form="$*"

    encoded=
base_str="${method}&$(url_encode "$url")&oauth_consumer_key%3D${key}%26oauth_nonce%3D${once}%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D${ts}%26oauth_token%3D${token}%26oauth_version%3D1.0"

    test -n "$form" && base_str+="%26$(url_encode "$form")"
    signature=$(printf "%s" "$base_str" | openssl dgst -sha1 -hmac $hmac -binary | openssl base64 | url_encode)

    oauth_header="Authorization: OAuth oauth_consumer_key=\"$key\", oauth_nonce=\"$once\", oauth_signature=\"$signature\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"$ts\", oauth_token=\"$token\", oauth_version=\"1.0\""

    test "$method" = "GET" && minus_g="-G"

    errfile=/tmp/shwitter.err
    curl -D $errfile $minus_g -X $method "$url" --header "$oauth_header" -d "$form" || cat $errfile >&2
}

op="$1"
shift
case "$op" in
    tweet)
        api_call POST 'https://api.twitter.com/1.1/statuses/update.json' "status=$(url_encode "$*")"
    ;;
    timeline)
        api_call GET 'https://api.twitter.com/1.1/statuses/home_timeline.json'
    ;;
    encode)
        url_encode "$*"
    ;;
    *)
        api_call $op $@
    ;;
esac
