#!/bin/bash

set -x

#only one at a time (simplifies hotkey daemon handling)
test "$(pgrep -c swin)" = "1" || exit

desk="$(wmctrl -d | grep \* | scut 0)"
windows="$(wmctrl -l | grep "^\S\+\s\+$desk" | scut 0,3-)"
winCount=$(($(printf '%s' "$windows" | wc -l)+1)) # TODO: why does this come up one short?
notificationId=1337
focusIdx=$(printf '%s' "$windows" | grep -m 1 -n $(pfw) | grep -o '^[0-9]*') # TODO: do or don't use wmutils

getFocus() {
    printf '%s' "$windows" | sed "$focusIdx p;d" | scut 0
}

mvFocus() {
    echo mvFocus $1

    focusIdx=$((focusIdx+$1))
    ((focusIdx<1)) && focusIdx=$((winCount))
    ((focusIdx>winCount)) && focusIdx=1

    wmctrl -i -a $(getFocus)
    notify
}

notify() {
    focus=$(getFocus)
    feedback -r $notificationId -t 0 "$(printf '%s' "$windows" | sed "s/$focus \(.*\)$/<b>--> \1<\/b>/" | sed 's/^0x[0-9a-fA-F]\+ /    /')"
}

notify

xsk | while read evt; do
    case "$evt" in
        "j 1") mvFocus 1;;
        "k 1") mvFocus -1;;
        Super_*\ 0)
            feedback -x $notificationId
            exit
        ;;
    esac
done

