#!/bin/sh
#dmenu $@ -l 50 -i -nb '#000000' -sb '#202020' -nf '#ff00ff' -sf '#ffeeff'
if [[ $1 == '--no-refocus' ]]; then
    NOFOCUS=1
    shift
fi

if [ -z $DISPLAY ] || ! (xrandr > /dev/null); then
    slmenu $@ -b -i -l $((`tput lines`-1))
else
    [ -z $NOFOCUS ] && WINDOW=`xprop -root _NET_ACTIVE_WINDOW | scut 4`
    dmenu $@ -l 50 -i -t
    # re-focus the window that was focused before we ran
    [ -z $NOFOCUS ] && wmctrl -i -a $WINDOW &> /dev/null
fi
