#!/bin/sh
if test "$1" = "--no-refocus"; then
    NOFOCUS=1
    shift
fi

if ! canx; then
    slmenu "$@" -b -i -l $(($(tput lines)-1))
else
    [ -z $NOFOCUS ] && WINDOW=$(xdotool getactivewindow)
    dmenu -l 50 -i -t "$@"
    # re-focus the window that was focused before we ran
    [ -z $NOFOCUS ] && bringwindow -a "$WINDOW" > /dev/null 2>&1
fi
