#!/bin/sh
#dmenu $@ -l 50 -i -nb '#000000' -sb '#202020' -nf '#ff00ff' -sf '#ffeeff'
if [ -z $DISPLAY ]; then
    slmenu $@ -b -i -l $((`tput lines`-1))
else
    WINDOW=`xprop -root _NET_ACTIVE_WINDOW | scut 4`
    dmenu $@ -l 50 -i -t
    # re-focus the window that was focused before we ran
    wmctrl -a -i $WINDOW &> /dev/null
fi
