#!/usr/bin/python2

import markdown2
import sys

onMarkdown = False
markdownBlock = ""

def printMarkdownBlock():
    if onMarkdown:
        global markdownBlock
        sys.stdout.write(markdown2.markdown(markdownBlock))
        markdownBlock = ""

for line in sys.stdin:
    if line.startswith('<<<<'):
        printMarkdownBlock()

        onMarkdown = not onMarkdown
    else:
        if onMarkdown:
            markdownBlock += line
        elif line is not None:
            sys.stdout.write(line)

# we might still have some pending markdown:
printMarkdownBlock()
