#!/bin/bash
                        if ! printf "%s" "$ES_FIELD_FROM" | grep -qi "$USER@$( hostname )"; then
                            feedback "Chat from $ES_FIELD_FROM" "$ES_FIELD_DATA"
                        fi
